import Head from "next/head";

const SEO = ({ title, desc }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name={desc} content="Generated by create next app" />
      <link rel="icon" href="/logo.svg" />
    </Head>
  );
};

export default SEO;
